services:
  green:
    image: 211125297893.dkr.ecr.ap-northeast-2.amazonaws.com/sscanner-backend
    container_name: green-server
    ports:
      - "8082:8080"
    environment:
      - HOME_URL
      - HOME_USERNAME
      - HOME_PASSWORD
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - AWS_REGION
      - REDIS_HOST
      - REDIS_PORT
      - BUCKET_NAME
      - BASE_URL
      - JWT_SECRET
      - SPRING_PROFILES_ACTIVE
      - COOLSMS_API_KEY
      - COOLSMS_API_SECRET
      - COOLSMS_PHONE_NUMBER
      - STACK_VERSION
      - ELASTIC_USERNAME
      - ELASTIC_PASSWORD
      - KIBANA_PASSWORD
      - CLUSTER_NAME