services:
  blue:
    image: 211125297893.dkr.ecr.ap-northeast-2.amazonaws.com/sscanner-backend
    container_name: blue-server
    ports:
      - "8081:8080"
    environment:
      - HOME_URL
      - HOME_USERNAME
      - HOME_PASSWORD
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - AWS_REGION
      - REDIS_HOST
      - REDIS_PORT
      - BUCKET_NAME
      - BASE_URL
      - JWT_SECRET
      - SPRING_PROFILES_ACTIVE
      - COOLSMS_API_KEY
      - COOLSMS_API_SECRET
      - COOLSMS_PHONE_NUMBER