name: CI Pipeline

on:
  push:
    branches:
      [develop, main, feature/25-ci-파이프라인-구축] # 테스트용
  pull_request:
    branches:
      [develop, main]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기(임시 데이터베이스 정보)
        run: echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: 빌드 및 테스트
        run: ./gradlew clean build
